### ISSUE TITLE
Suggestion: usage of Z-engine for the 4.x version

### ISSUE THREAD

**Issue by lisachenko** [opis/closure#101]
Hi! I’m author of the `lisachenko/z-engine` library. I’ve noticed that your library also using FFI to do some low-level tricks, which is really cool! Even some parts in your library are looking very similar :)

I’m trying to create a package that can be used as a platform for creation of low-level extensions for PHP, written in PHP language itself. And I can see that there is an opportunity to collaborate on making our libraries more maintainable and useful by using my Z-engine as low-level platform for your library and removing extra-complexity from the `opis/closure`.

Please, share your opinion about this possible integration and reply if you will be interested in this )

BR, Alex

**Comment by sorinsarca** [comment]
We abandoned the idea of using ffi.
