### ISSUE TITLE
Backport PHP 8.1 support to 3.x

### ISSUE THREAD

**Issue by GrahamCampbell** [opis/closure#102]
I will handle this task next week. Related: https://github.com/opis/closure/commit/48557b54f6bf12cd85db14a7cf0c05656c6ce363.

**Comment by nunomaduro** [comment]
@GrahamCampbell This can be closed, as we will be maintaining our own fork.

**Comment by xpader** [comment]
fork???

**Comment by GrahamCampbell** [comment]
Because we had to make breaking changes to get it to work, and the 4.x branch on this repo is already reserved for the FFI version, which is currently unsuitable for use with php-fpm.

**Comment by sorinsarca** [comment]
@GrahamCampbell can you tell me why is not (properly) working with php-fpm? 
I've used php-fpm to test it and I had no issues

**Comment by nunomaduro** [comment]
It may work with PHP FPM, but it's simply not enabled by default.

**Comment by sorinsarca** [comment]
You mean the ffi extension?

**Comment by nunomaduro** [comment]
@sorinsarca Correct. Edited my previous comment.

**Comment by GrahamCampbell** [comment]
It's also very slow to initialize, and there have been no improvements to address told starts with fpm.

**Comment by sorinsarca** [comment]
It is slower in dev mode, when you don't use preloading. Try it with preload enabled

You just have to add in your preload file a single line

```php
\Opis\Closure\Library::preload();
```

**Comment by xpader** [comment]
I think we still need `no FFI version`, or auto detect and use FFI when it's enabled.
