### ISSUE TITLE
Laravel installation error 

### ISSUE THREAD

**Issue by rami1973** [opis/closure#104]
when I install new laravel project getting:
In SerializableClosure.php line 18:

  Opis\Closure\SerializableClosure implements the Serializable interface, whi
  ch is deprecated. Implement __serialize() and __unserialize() instead (or i
  n addition, if support for old PHP versions is necessary)

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by GrahamCampbell** [comment]
This package doesn't support PHP 8.1. From Tuesday afternoon next week, Laravel 8 will partially support PHP 8 via a fork of this package (needed to make various breaking changes). I would warn against using Laravel 8 with PHP 8.1 in production at the moment. There are various known issues, still, and some that won't be fixed (such as full support for using mail on PHP 8.1... people will have to wait until Laravel 9).

**Comment by rami1973** [comment]
so I should downgrade php 8.1 to 8.0

**Comment by GrahamCampbell** [comment]
Yes. PHP 8.1 is not ready for production use yet, and neither is Laravel on PHP 8.1.
