### ISSUE TITLE
autoload.php may not load the proper functions.php depending on CWD

### ISSUE THREAD

**Issue by randstring** [opis/closure#109]
Hello,

This is quite a great library and works flawlessly, but I noticed a minor issue, which might be related to the way I use it.

Instead of using composer, I've integrated a version of the library in my source and load it using
`require_once('closure/autoload.php');`

Now, autoload.php has `require_once 'functions.php';` which depending on the caller script location (and thus working directory), sometimes tries to load another functions.php from my project, because it does not specify a location. Shouldn't this become `require_once __DIR__.'/functions.php'` to make sure the proper one is required? Or would this conflict with Composer or some other intended way of usage?

Thank you.

**Comment by sorinsarca** [comment]
The autoload file is there if you want to use this lib without composer, so that line can become
```php
require_once __DIR__ . '/functions.php';
```

@randstring can you submit a PR?

**Comment by randstring** [comment]
Thank you. I just did.

**Comment by sorinsarca** [comment]
v3.6.3 was released
