### ISSUE TITLE
Closures with contexts and circular references.

### ISSUE THREAD

**Issue by andaniel05** [opis/closure#11]
Thanks for solve very faster my last reported issue. My english is not good and i do not can comment more about. This is the problem:

```php
<?php

require_once '../vendor/autoload.php';

use function Opis\Closure\{serialize as s, unserialize as u};

$child = new \stdClass();
$parent = new \stdClass();

$child->parent = $parent;

$parent->children = [$child];
$parent->closure = function () use ($child) {};

$result = s($parent);
u($result); // PHP Fatal error: Maximum function nesting level of '256' reached, aborting! in ...\vendor\opis\closure\src\SerializableClosure.php on line 397

```

**Comment by msarca** [comment]
This was fixed in 3.0.4. There are still some [edge cases](https://github.com/opis/closure/blob/master/tests/ClosureTest.php#L114) that require further investigation, since it might be a PHP internal bug.
