### ISSUE TITLE
Error using `opis/closure` in PHP 8

### ISSUE THREAD

**Issue by matheusjohannaraujo** [opis/closure#114]
PHP 8.1.2 (XAMPP) - Windows 10 Pro x64

![image](https://user-images.githubusercontent.com/47996428/157938990-b82ac36d-aa67-418b-ad3b-390af95ffe09.png)

**Comment by matheusjohannaraujo** [comment]
https://php.watch/versions/8.1/serializable-deprecated

**Comment by GrahamCampbell** [comment]
Version 3 of this package does not work on PHP 8.1. You need to either use the version 4 beta, or `laravel/serializable-closure`, instead.
