### ISSUE TITLE
Should closures with `$this` keyword be wrapped in an additional closure?

### ISSUE THREAD

**Issue by nmeri17** [opis/closure#117]
The examples in the docs referring to `$this` all use classes, but I just want to serialize a closure, not the entire class. I'm passing the following closure to the serializer
```php
function () use ($outerVar) {

	return $outerVar . "/" . $this->myProperty;
}
```
And it throws the error "PDOException: You cannot serialize or unserialize PDO instances". I don't have a PDO instance anywhere close to where this closure is sent down to serializer. I realized other closures work without the `$this` keyword, combined with clues from reading other issues, I wrapped closure in additional closure
```php
function () use ($outerVar) {

	return function () use ($outerVar) {

		return $outerVar . "/" . $this->myProperty;
	};
}
```

And error disappeared during serialization, but issue still stands. See next paragraph. I'm able to serialize and unserialize, but this doesn't seem to be intended use since I can't bind `$this` to context where closure is unserialized at. When I unserialize like so:
```php
public function evaluateClosure (callable $receivedClosure) {
	$callable = unserialize($receivedClosure)->getClosure();

	$callable->bindTo($this, $this); // so dev can have access to `myProperty`
	// also tried ->bindTo(null)

	var_dump($callable()); // returns the outer closure
```
Then, going further to call `$callable()()` results in "Error: Using $this when not in object context". Is this a serialization problem or a binding one?

**Comment by nmeri17** [comment]
Update: My bad. I just realised `bindTo` doesn't modify original closure but returns a new instance. I should have assigned the result of `$callable->bindTo($this, $this);`

You can close issue after confirming closure should be doubly wrapped

**Comment by sorinsarca** [comment]
In version 4.0 you should be able to add custom serializers.
https://opis.io/closure/4.x/objects.html
