### ISSUE TITLE
Issue with php 8.1

### ISSUE THREAD

**Issue by LordDeveloper** [opis/closure#120]
PHP Deprecated:  Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

**Comment by GrahamCampbell** [comment]
The 4.x branch does not support PHP 8.1 or higher. You need to use the pre-release 5.x series or the Laravel version of this package.
