### ISSUE TITLE
error:php8  Serializable interface is deprecated

### ISSUE THREAD

**Issue by kiss291323003** [opis/closure#127]
php version:8.1.10
error file:opis/closure/src/SerializableClosure.php on line 18
error msg:Deprecated: Opis\Closure\SerializableClosure implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary)

**Comment by jdreesen** [comment]
This bundle is not compatible with PHP 8.1.

**Comment by GrahamCampbell** [comment]
Duplicate of https://github.com/opis/closure/issues/126.
