### ISSUE TITLE
Not compatible with PHP 8.1

### ISSUE THREAD

**Issue by charescape** [opis/closure#128]
PHP Fatal Error with message 'During inheritance of ReflectionFunctionAbstract: Uncaught ErrorException: Return type of Opis\Closure\ReflectionClosure::isStatic() should either be compatible with ReflectionFunctionAbstract::isStatic(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /code/vendor/opis/closure/src/ReflectionClosure.php:49

**Comment by charescape** [comment]
@jdreesen The latest version: 3.6.3

**Comment by jdreesen** [comment]
It's not compatible with PHP 8.1. You can use [Laravel's fork](https://github.com/laravel/serializable-closure) or the [experimental FFI version](https://github.com/opis/closure/issues/59) of this package.

**Comment by charescape** [comment]
@jdreesen It's helpful, thank you! But I still want to know is there any plan to fix for this library?

**Comment by GrahamCampbell** [comment]
There are no plans to fix it, as far as I'm aware.
