### ISSUE TITLE
Cannot serialize Swift_Transport_AbstractSmtpTransport

### ISSUE THREAD

**Issue by henarozz** [opis/closure#137]
When I try to serialize a complex object that has a nested SwiftMailer object, I get the error "Cannot serialize Swift_Transport_AbstractSmtpTransport"

PHP 7.1
"yiisoft/yii2-swiftmailer": "~2.0.0 || ~2.1.0"

**Comment by sorinsarca** [comment]
Version 4.0 supports arbitrary data serialization, you should be able to register a serializer for 'Swift_Transport_AbstractSmtpTransport'.
https://opis.io/closure/4.x/objects.html
