### ISSUE TITLE
Serializing something that references Laravel IoC Container causes it to be emptied out

### ISSUE THREAD

**Issue by Blizzke** [opis/closure#15]
I just spend a couple hours tracking this down and it's a doozy. 

When serializing a Closure that somehow references the `Illuminate\Container\Container` object, the serialization process will break the container (and the rest of the code because of it).

The problem occurs when it encounters the static `$instance` property of the Container and tries to do a `$property->setValue($data, $value);` on it. This call causes a near complete wipe of the containers' contents.

For me the problem occurred because my class had an eloquent `Model` property (which references the `DatabaseManager`, which references the `Application`, which in turn is a `Container`).

I don't know if anything can be done about this, but I at least wanted it on the record so that future me (and other people) hopefully have to spent less time on finding this

On the line in question:
<img width="1540" alt="screen shot 2017-10-31 at 17 10 45" src="https://user-images.githubusercontent.com/231572/32235358-8dcc9612-be5f-11e7-9236-664a1211af88.png">

After executing the line:
<img width="1541" alt="screen shot 2017-10-31 at 17 11 01" src="https://user-images.githubusercontent.com/231572/32235357-8dad84fc-be5f-11e7-869f-355432840dbc.png">

**Comment by GrahamCampbell** [comment]
You cannot serialize the laravel container I'm afraid. Laravel has a very specific mechanism for serialzing eloquent models. See it's queue source code. :)

**Comment by Blizzke** [comment]
Well aware of that, as a matter of fact, I'm pretty glad the SuperClosure was removed from earlier versions and replaced by reflection. 
Unfortunately this was using the BotMan component. For conversations it just serializes the entire bot instance. Some code of mine contained a reference to an eloquent model.
In any case: Beware.

**Comment by msarca** [comment]
Static properties were not supposed to be processed, since they are not serializable.
The issue was fixed in v3.0.7, but I doubt it will solve your problem because of static variables used by Laravel. Anyhow, let me know if it works for you or not.

**Comment by mpociot** [comment]
@Blizzke Serializing the conversations is the simplest way of adding a conversation cache to BotMan, with the expressive API that I want to keep. I know that it might introduce jumping through some hoops though.
Let me know if you think we can improve this in the BotMan codebase 👍

**Comment by Blizzke** [comment]
I don't think there's an easier way for Botman to keep track of the conversation state that via serializing the object. It's the best way to do it.
It's unfortunate that I had to find out that way :)
Perhaps the docs could somehow warn you about the fact that everything is being serialized and "watch out for IoC containers like laravel" etc? (Or did I miss this already being in there?)

What I was thinking about is that perhaps the SuperClosure could provide a way to add handlers that take care of specific object types. Like if an instance of type X is encountered to serialize, use this handler. Using it would be optional, obviously. Thos would allow you to just save a class name and an id, like laravel's `SerializesAndRestoresModelIdentifiers`. This would definitely allow you to stop the serialisation earlier as well and avoid including data you don't need. Or someone could come up with a package for a framework that supports the most common types.

Anyway, I know now, so I can work around it :)
