### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by MarcAtEnopTeam** [opis/closure#16]
Hi, let me introduce an issue regarding namespaces.

My closure is kind of :

`function () {
$class = 'Full\Name\Space';
  new $class();
}`

But it is my closure in declared in namespace SomeOther

So when it is serialized => closure becomes that :

`function () {
$class = 'Full\Name\Space';
  new \SomeOther$class();
}`

And, guess what happend on execute => Yeah, a nice parse error.

Is there a kind of params to set for SerializableClosure do not attempt to fully qualified new object();

**Comment by msarca** [comment]
When instantiating a class from a variable is better to use its [fully qualified namespace](http://php.net/manual/ro/language.namespaces.rules.php). So using `\Full\Name\Space` instead of `Full\Name\Space` should solve this issue

**Comment by MarcAtEnopTeam** [comment]
Nope, it is not.

My real object have a full qualified namespace: \Full\Namespace.  What is wrong with that, is supreclosure always put a namespace before $class, and because it is a variable i have a parse error.

**Comment by MarcAtEnopTeam** [comment]
An other example, try to serialize this kind of closure :

`function ($FullClassName) {
  new $FullClassName();
}`

result in :

`function ($FullClassName) {
  new \$FullClassName();
}`

And we've got a nice parse error :/

**Comment by MarcAtEnopTeam** [comment]
I have notice SerializableClosure put namespace regarding of the last is thinking to have it. But if you have somewhere a string it look like a namespace, so it take that namespace for it.

Example :

`function () {
    $class = '\Full\Path\To\Subdirectory\' . \Road\To\A\Class::CONSATANT . '\I\Want\It';
    new $class();
}`

Result in :

`function () {
    $class = '\Full\Path\To\Subdirectory\' . \Road\To\A\Class::CONSATANT . '\I\Want\It';
    new \Road\To\A\Class$class();
}`

Hope this help

**Comment by MarcAtEnopTeam** [comment]
Maybe the simplest (not the best) solution is to ignore finded spacename before $

**Comment by msarca** [comment]
I've manage to fix this. I will release a patch version in the following minutes.

**Comment by MarcAtEnopTeam** [comment]
I have try your 
Fixes parse error #16
for example :

function ($FullClassName) { new $FullClassName(); }

result in :

function ($FullClassName) { new \$FullClassName(); }

And it works great,

... but not for the second example

**Comment by msarca** [comment]
The v3.0.8 patch is out. Thanks for reporting this bug. It should be fixed now.

**Comment by MarcAtEnopTeam** [comment]
let's go and make a try :)

**Comment by MarcAtEnopTeam** [comment]
Work great!!!

**Comment by MarcAtEnopTeam** [comment]
Nice done!
