### ISSUE TITLE
Strange require_once error

### ISSUE THREAD

**Issue by theofidry** [opis/closure#33]
I'm trying to leverage `opis/closure` to make sure one of my class is serializable. For full details, you can check the concerned PR: https://github.com/humbug/box/pull/406/files

TL:DR; since I'm using this, I can observe a very strange error:

```php
PHPUnit\Framework\Exception: PHP Fatal error:  require_once(): Failed opening required 'closure://static function () use ($whitelistedFiles): \Humbug\PhpScoper\Scoper {
                $scoper = (new class() extends \Humbug\PhpScoper\Console\ApplicationFactory {
                    public static function createScoper(): \Humbug\PhpScoper\Scoper
                    {
                        return parent::createScoper();
                    }
                })::createScoper();

                if ([] !== $whitelistedFiles) {
                    return new \Humbug\PhpScoper\Scoper\FileWhitelistScoper($scoper, ...$whitelistedFiles);
                }

                return $scoper;
            }' (include_path='.:/path/to/.phpbrew/php/php-7.2.14/lib/php/pear') in Standard input code on line 672
PHP Stack trace:
PHP   1. {main}() Standard input code:0

Fatal error: require_once(): Failed opening required 'closure://static function () use ($whitelistedFiles): \Humbug\PhpScoper\Scoper {
                $scoper = (new class() extends \Humbug\PhpScoper\Console\ApplicationFactory {
                    public static function createScoper(): \Humbug\PhpScoper\Scoper
                    {
                        return parent::createScoper();
                    }
                })::createScoper();

                if ([] !== $whitelistedFiles) {
                    return new \Humbug\PhpScoper\Scoper\FileWhitelistScoper($scoper, ...$whitelistedFiles);
                }

                return $scoper;
            }' (include_path='.:/path/to/.phpbrew/php/php-7.2.14/lib/php/pear') in Standard input code on line 672

Call Stack:
    0.0036     695856   1. {main}() Standard input code:0
```

My changes are not very big, it's mostly:

- https://github.com/humbug/box/pull/406/files#diff-800cea1ed68365ce5611da002643277aR2847
- https://github.com/humbug/box/pull/406/files#diff-85e4bcd50593e4cd70c93577b56e2704R1

It's only a gut feeling but this looks related to PHPUnit running some tests in separate processes.

For reproducing: you can checkout the linked PR and run `composer install && bin/phpunit`

**Comment by msarca** [comment]
This probably happens because of `vfsStream`, of which I suppose that it's used in order to make all those `final` classes mockable, so that `PHPUnit` could run tests against them. Anyway, you could easily fix this by adding the following line in `tests/boostrap.php`.

```php
\Opis\Closure\ClosureStream::register();
```

**Comment by theofidry** [comment]
Brillant that did the trick. I completely forgot about that vfsStream. Thanks very much for the quick and spot on reply :)
