### ISSUE TITLE
Serializing short closures does not work

### ISSUE THREAD

**Issue by davidbyoung** [opis/closure#41]
It appears as though short closures aren't serialized correctly.  When running the following example, I get this error message:

```
include(): Opis\Closure\ClosureStream::stream_set_option is not implemented!
C:\Users\me\PhpstormProjects\opis-test\vendor\opis\closure\src\SerializableClosure.php:257
```

```php
$expectedClosure = fn () => 1;
$serializedClosure = \Opis\Closure\serialize($expectedClosure);
$actualClosure = \Opis\Closure\unserialize($serializedClosure );
assert($actualClosure() === 1);
```

According to [bugs.php.net](https://bugs.php.net/bug.php?id=78375), this is a deliberate backwards compatibility break, and hasn't been documented.  This will probably require a code change.

**Comment by davidbyoung** [comment]
I should also note that if I update `ClosureStream` by adding `stream_set_option` as per [the official PHP upgrade guide](https://github.com/php/php-src/blob/php-7.4.0RC5/UPGRADING#L41):

```php
function stream_set_option(int $option, int $arg1, int $arg2)
{
    return false;
}
```

...I get a different error with my original example on the line where I invoke `$actualClosure()`:

```
Error : Function name must be a string
```

**Comment by msarca** [comment]
Support for short closures was added in [v3.5.0](/opis/closure/releases/tag/3.5.0)

**Comment by davidbyoung** [comment]
Oh, excellent!  Thank you so much!  I'll check it out.
