### ISSUE TITLE
Version 3.5.1 does not work with Drupal module Views PHP

### ISSUE THREAD

**Issue by hoorack** [opis/closure#50]
When following issue [https://www.drupal.org/project/views_php/issues/2274543#comment-13440289](https://www.drupal.org/project/views_php/issues/2274543#comment-13440289), I had to downgrade the Closure library to version 3.4.1 to make it work.

**Comment by joejoseph00** [comment]
Thanks @hoorack for reporting, yes 3.4.1 works fine.

**Comment by joejoseph00** [comment]
not sure why 3.5.1 wouldn't work, but I think perhaps someone has found another approach that does not use the closure library.  Anyhow, thanks for your support to get 3.4.1 working.
