### ISSUE TITLE
Unbinding $this of closure is deprecated on php 7.4

### ISSUE THREAD

**Issue by envatic** [opis/closure#56]
`ErrorException {#1613
  #message: "Unbinding $this of closure is deprecated"
  #code: 0
  #file: "./vendor/opis/closure/src/SerializableClosure.php"
  #line: 263
  #severity: E_DEPRECATED
  trace: {
    ./vendor/opis/closure/src/SerializableClosure.php:263 { …}
    Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() {}
    ./vendor/opis/closure/src/SerializableClosure.php:263 { …}
    Opis\Closure\SerializableClosure->unserialize() {}`

**Comment by sorinsarca** [comment]
@envatic Please post an example in order to reproduce your issue.

**Comment by envatic** [comment]
php7.4 no longer allows this,
`$closure->bindTo(null)`
[https://wiki.php.net/rfc/deprecations_php_7_4#unbinding_this_from_non-static_closures](url)

**Comment by msarca** [comment]
@envatic I can' t reproduce this on PHP v7.4.6.

**Comment by sorinsarca** [comment]
@envatic you are wrong, `$closure->bindTo(null)` is allowed if closure is "static".

```php
error_reporting(E_ALL);
$f = function () {return 123;};
echo $f->bindTo(null)();
```

In this case, it shows the warning

```php
error_reporting(E_ALL);

class A {
    public $prop = 123;

    function test() {
        return function () {
            return $this->prop;
        };
    }
}

$f = (new A())->test();
$f->bindTo(null);
```

**Comment by sorinsarca** [comment]
So, opis/closure should detect that there is an `$this` inside closure. The question is why you don't have the object serialized? That's why I needed an example.

**Comment by msarca** [comment]
I will reopen this issue if OP provides a reproducible example that involves opis/closure.

**Comment by oleghalin** [comment]
Im using botman and `repeat()` function after first fall returns this error.

**Comment by oleghalin** [comment]
@msarca take a look into it please.

**Comment by msarca** [comment]
@oleghalin Maybe's Botman's fault for that warning message? I'm not familiar with the its internals and I don't have the time to dive in into its source code. Could you provide something reproducible that doesn't require setting up an entire stack? Thanks.

**Comment by oleghalin** [comment]
@msarca I finally found time to check this. The issue is related to that closure was unserialized first, then Closure was serialized again and it doesn't have `this` attribute. Is there a way to bind `$this` to newly serialized closure?

**Comment by oleghalin** [comment]
@msarca basically here is 2 Closures, which I try to serialize. I figured out that issue is related to "isBindingRequired" is false for a second.
![image](https://user-images.githubusercontent.com/9086983/96768225-48387f00-13e6-11eb-8f7f-9a42683f961a.png)
![image](https://user-images.githubusercontent.com/9086983/96768204-41117100-13e6-11eb-9a39-8c66929ba04a.png)
