### ISSUE TITLE
'$this' getting lost when closure calling another closure is serialized

### ISSUE THREAD

**Issue by phestermcs** [opis/closure#6]
Glad there's someone taking on serialized PHP closures, so thank you for that. However, the following seems broken. Is this by design, or is this a bug? Would greatly like this to be an easily fixed bug. Took a dependency on opis/closure, and this problem is preventing it's use on a critical project... :( 

// [PHP 5.6.13]
```php
require_once 'vendor/autoload.php';
function two($closure) {
	$wrapped = function() use($closure) {
		$closure();
	};

	// this correctly outputs 'Test';
	$x = new \Opis\Closure\SerializableClosure($wrapped, true);
	$x();

	// this outputs 'Opis\Closure\SerializableClosure'
	$x = unserialize(serialize($x));
	$x();
}

class Test
{
	function one() {
		two(function() {
			echo get_class($this). "\n";
		});
	}
}

$t = new Test();
$t->one();
```

**Comment by phestermcs** [comment]
It appears this is because serializing a closure's $this is opt in rather than opt out, and the above never allows for opting in for the passed closure (the closure passed to function two()). To test for my use, I just changed line 307 of SerializableClosure to always be true and my problem was worked around; i.e. to in effect always serialize the object a closure is bound to.

This obviously is not a long term fix. I would suggest that serializing the object a closure is bound to be opt out rather than opt in, as I believe it is more often the case one would want to serialize the bound object than not; at least this is so in my scenario, which is orders of magnitude more complex than the sample I had above (spent the whole day chasing this bug, or whatever to call it, down).

There would still of course be the issue of opting out in a similar pattern above, but being that would be the exception, the user could simply bind the closure to null before passing.

**Comment by msarca** [comment]
Hello. Indeed this is a bug. Fortunately it is a small bug. I will issues a new version in a few minutes.

**Comment by phestermcs** [comment]
Thanks.. line 240 of SerializableObject might be problem too

**Comment by phestermcs** [comment]
btw, was first using closure serialization from jeremeamia. your's is like a million times better. THX!!

**Comment by phestermcs** [comment]
fixed! thx again

**Comment by msarca** [comment]
Thank you for reporting this bug
