### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by driesvints** [opis/closure#63]
We've started looking into PHP 8 builds for laravel/framework. We'll need a release of opis/closure or a nightly build for a next major version that allows for PHP 8 in its requirements. Nothing urgent but would be cool to set up soon.

**Comment by sorinsarca** [comment]
@driesvints PHP 8 support is on branch 4.x 

Releated: #59

**Comment by GrahamCampbell** [comment]
Upgrading to 4.x is non-trivial, and involves abandoning PHP 7.2 and 7.3. Laravel 6 LTS uses this library and needs support for PHP 7.2-8.0 all in the same version, or at least a version that doesn't involve adding extra initialisation steps to get the library to work like v4 needs. I'd be happy to help with enabling PHP 8 in v3 of this package, since it will be some number of years before Laravel is able to upgrade to v4.

**Comment by GrahamCampbell** [comment]
NB Laravel 6, 7, 8 and 9 will all be using v3. Possibly Laravel 10 (planned for September 2021) will be able to upgrade to v4.

**Comment by GrahamCampbell** [comment]
Also, am I right in thinking initialization in v4 is very slow if preloading is not used?

**Comment by sorinsarca** [comment]
> Also, am I right in thinking initialization in v4 is very slow if preloading is not used?

I made a few simple tests on my machine, the initialization is about 30ms using an optimized autoloader and only 12ms if I manually add a few calls to `class_exists` prior initialization to bypass the autoloader.
 
With preloading initialization should take about 0.02ms, which can be ignored.

It is slower but I wouldn't say very slow given that the autoloader takes 60% and no one cares.

**Comment by GrahamCampbell** [comment]
I'd also be counting this FFI compile time as initialisation? How slow is https://github.com/opis/closure/blob/4.x/src/HeaderFile.php#L52-L70 when preloading is not enabled?

**Comment by GrahamCampbell** [comment]
Interesting. I was expecting FFI to be much slower without preloading. 30ms is certainly a lot though. It is still this slow after opcache has warmed up?

**Comment by sorinsarca** [comment]
> Interesting. I was expecting FFI to be much slower without preloading. 30ms is certainly a lot though. It is still this slow after opcache has warmed up?

Tests without preloading were made with php cli without opcache. 
Tests with preload enabled were made using the phps builtin server.

I'll try to test it on a server with opcache enabled.

**Comment by driesvints** [comment]
@sorinsarca thanks for your help so far btw! :)

**Comment by msarca** [comment]
@GrahamCampbell We'll definitely need help for maintaining v3, especially if we're talking about years of maintenance. If you are willing to jump on board, I'll send you an invite to our organization.

**Comment by GrahamCampbell** [comment]
I'd be happy to help out. Please do let me know if there are any urgent outstanding issues in v3 that you'd like help with, and I'll see what I can do. :)
