### ISSUE TITLE
functions.php a bad idea

### ISSUE THREAD

**Issue by GrahamCampbell** [opis/closure#65]
https://github.com/opis/closure/blob/4.x/composer.json#L33 loads a functions.php file. Note that this will lead to a fatal error if someone globally installs opis and also locally installs it. I'd instead recommend making the init function a static class method. PHP's autoloader was built to load classes, not functions, basically.

NB Other libraries like illuminate/support get around this by conditionally defining their functions, but this would not be a good solution for opis, since it really matters you get the correct function. This also really matters for Guzzle, which is why we moved to static class methods after we got bitten by this: https://github.com/guzzle/guzzle/issues/2511, https://github.com/guzzle/guzzle/pull/2548, https://github.com/guzzle/guzzle/pull/2546.

**Comment by sorinsarca** [comment]
I've just removed the functions.php file, please check the readme file https://github.com/opis/closure/blob/4.x/README.md

**Comment by GrahamCampbell** [comment]
Perfect. :)
