### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by yceruto** [opis/closure#8]
Hi, first thank you for this awesome library! 

I've a problem serializing this context:
```
class Foo
{
    private $options;

    public function __construct()
    {
        $this->options['is_valid'] = function () {
            return true;
        };
    }
}

$foo = new Foo();

$serializable = new SerializableClosure(function () use ($foo) {
    // do something.
});

serialize($serializable);
```

It throws the exception because `use` objects are not mapped in `mapByReference()` (unless being `\stdClass`), it can happen into `$this` context too. Any suggestion?

**Comment by msarca** [comment]
Hello. The problem here is within the `Foo` class. It contains properties that store closures which are not wrapped by an instance of `SerializableClosure`class. Trying to serialize an instance of `Foo` will result in the same exception being thrown. 

```php
serialize(new Foo()); // Serialization of 'Closure' is not allowed
```
The best solution would be to implement the [Serialize](http://php.net/manual/ro/class.serializable.php) interface.
```php
class Foo implements Serializable
{
    private $options;

    public function __construct()
    {
        $this->options['is_valid'] = function () {
            return true;
        };
    }

    public function serialize()
    {
        $options = $this->options;
        SerializableClosure::enterContext();
        foreach($options as &$value){
              if($value instanceof Closure){
                   $value = SerializableClosure::from($value);
              }
        }
        SerializableClosure::exitContext();
        return serialize($options);
    }
    
    public function unserialize($data)
    {
         $options = unserialize($data);
         foreach($options as &$value){
              if($value instanceof SerializableClosure){
                     $value = $value->getClosure();
              }
         }
         $this->options = $options;
    }

}
```

**Comment by yceruto** [comment]
Yes, sadly I show you only a sample of the real context, this Foo class belong to a third-party library. For example, into Symfony controller I can't use `$this` or to pass instances (throught  `use`) like `EntityManager`, `QueryBuilder`, `Query`, and so on.

**Comment by msarca** [comment]
There is now a [3.0.x-dev](https://github.com/opis/closure/tree/3.0) version available that can handle objects referenced with `use`.  A stable version will be available soon.
```php
class Foo
{
    private $options;

    public function __construct()
    {
        $this->options['is_valid'] = function () {
            return true;
        };
    }
}



$foo = new Foo();

$serializable = new SerializableClosure(function () use ($foo) {
    // do something.
});

serialize($serializable); // Works
``` 

Also, you can now serialize/deserialize arbitrary data using the newly introduced functions `Opis\Closure\serialize` and `Opis\Closure\unserialize`.


```php
use function Opis\Closure\{serialize, unserialize};

class Foo
{
    private $options;

    public function __construct()
    {
        $this->options['is_valid'] = function () {
            return true;
        };
    }
}

$foo = new Foo();

serialize(function() use($foo){
   // Works
});
serialize($foo); // This works also
``` 
Check it out and let me know if it solves your issue

**Comment by yceruto** [comment]
I'll try this ASAP! Thanks!

**Comment by yceruto** [comment]
Yes! It works on that simple context, but I have another problem now, some class have the magic method `__clone` as private and it throws an exception:

```
Call to private AppBundle\Foo::__clone() from context 'Opis\Closure\SerializableClosure'
```

This should be a new requirement now?

**Comment by msarca** [comment]
Fixed.

**Comment by yceruto** [comment]
Awesome! I'll try again today, thanks!

**Comment by yceruto** [comment]
:+1: Thank you very much! This work!

**Comment by alpipego** [comment]
May I reopend this? When I try to serialize a GuzzleHttp\Promise object and 

```
Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in /var/www/nh/vendor/opis/closure/src/SerializableClosure.php:154
Stack trace:
#0 /var/www/nh/vendor/opis/closure/src/SerializableClosure.php(154): serialize(Array)
#1 [internal function]: Opis\Closure\SerializableClosure->serialize()
#2 /var/www/nh/vendor/opis/closure/functions.php(30): serialize(Object(GuzzleHttp\Promise\Promise))
```

Any idea on how to work around it?

**Comment by msarca** [comment]
Yep, this is a bug! I've managed to reproduce it, and I will release a fix as soon as possible.

**Comment by msarca** [comment]
Fixed in 3.0.2. Just issue a `composer update` command and all should work fine. Thanks for reporting this bug and let me know how this fix works for you.

**Comment by alpipego** [comment]
Damn. Somehow missed this... It's working great. Thanks!

**Comment by wol-soft** [comment]
Broken with PHP8.4 again - if the repository is still maintained.
