### ISSUE TITLE
Use opis/closure without composer?

### ISSUE THREAD

**Issue by pwFoo** [opis/closure#82]
I would like to use opis/closure with a small project. 
But I don't use composer / directory structure.

Any chance that a simple package / library file is generated for single file / single directory usage?

**Comment by GrahamCampbell** [comment]
You can still use composer, even if this is the only package you load with it.

**Comment by pwFoo** [comment]
@GrahamCampbell 
And how to load without composer autoload? I use a custom autoload based on namespace and class name. 
My autoload failed with src directory or `../include/* structure wanted by opis/closure if I move files out of src sub directory.

**Comment by sorinsarca** [comment]
Just include our autoloader provided in the 'autoload.php' file.

**Comment by GrahamCampbell** [comment]
```php
<php

require_once __DIR__ . '/vendor.autoload.php';

// include the rest of your files

// your app startup code
```

**Comment by GrahamCampbell** [comment]
You could also use a classmap composer autoloader to include your "includes" for you too, so you'd just need to require the main autoload file.

**Comment by sorinsarca** [comment]
```php
<?php

require_once 'path-to-opis-closure/autoload.php';

// code
```

This is the autoloader (you don't need composer)
https://github.com/opis/closure/blob/master/autoload.php

**Comment by pwFoo** [comment]
Hi, I modified my autoload and now it works fine. Thanks
