### ISSUE TITLE
Apache 2.0 license in tests/JsonSerializableClosure.php

### ISSUE THREAD

**Issue by rgson** [opis/closure#86]
Most of the code is licensed under the MIT license, according to the LICENSE file, the README, and headers in the individual files. However, the single file [tests/JsonSerializableClosure.php](https://github.com/opis/closure/blob/master/tests/JsonSerializableClosure.php#L5) is instead licensed under the Apache 2.0 license, according to its header. This is easily missed.

Could it perhaps be re-licensed under MIT for consistency? Or could perhaps a note be added in the README to notify users of this deviation to licensing terms?

**Comment by sorinsarca** [comment]
Fixed in https://github.com/opis/closure/commit/6c5e882c80e1853906ed559bdb62966cb414aaf9
