### ISSUE TITLE
Trying to serialize a closure freezes PHP

### ISSUE THREAD

**Issue by kenygamer** [opis/closure#89]
## Issue description
Trying to serialize a closure gives you a segmentation fault error.

## Logs
```
Segmentation fault (core dumped)
``` 

## Context
The context is a ReactPHP loop, with two open resources (udp and wss socket).

My code is briefly like this, I cannot send more since it is a private project:

```php
function list() : array{
    return range(0, 10);
}
$loop = \React\EventLoop\Factory::create();
//initialization code
$loop->addTimer(1, function() : void{
    $closure = function() : void{
        $list = \list();
        $this->doSomething();
    });
    $test = serialize(new \Opis\Closure\SerializableClosure($closure));
});
$loop->run();
```

**Comment by sorinsarca** [comment]
Please provide: PHP version, opis/closure version, reactphp version

**Comment by kenygamer** [comment]
> Please provide: PHP version, opis/closure version, reactphp version

PHP version: 7.3.0
`opis/closure` version: 06b4961
ReactPHP version: 527e5cc

**Comment by kenygamer** [comment]
@sorinsarca

**Comment by sorinsarca** [comment]
@kenygamer I cannot reproduce your issue, so I don't know if it is related to opis/closure.

Please provide a detailed backtrace (use gdb, valgrind or similar). 
See 
https://bugs.php.net/bugs-generating-backtrace.php
https://bugs.php.net/bugs-getting-valgrind-log.php

**Comment by kenygamer** [comment]
> @kenygamer I cannot reproduce your issue, so I don't know if it is related to opis/closure.
> 
> Please provide a detailed backtrace (use gdb, valgrind or similar).
> See
> https://bugs.php.net/bugs-generating-backtrace.php
> https://bugs.php.net/bugs-getting-valgrind-log.php
I am not using php compiled with `--enable-debug` flag.

The error is with ReactPHP loops, using two sockets that I know. I'm trying to serialize a closure that calls a few methods in a class and I'm having the segmentation fault error described.

**Comment by sorinsarca** [comment]
> The error is with ReactPHP loops, using two sockets that I know. I'm trying to serialize a closure that calls a few methods in a class and I'm having the segmentation fault error described.

I know, but I cannot reproduce it.

> I am not using php compiled with --enable-debug flag.

Ok, then use docker or something to install a debug version of php.

If you cannot provide a sample code to reproduce the issue I cannot help you.

**Comment by sorinsarca** [comment]
Please reopen when you have more details
